github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true

tasks:
  - init: pip3 install -r requirements.txt
    command: python3 main.py